### PR TITLE
add "sol" to AuthType (Typescript)

### PR DESCRIPTION
**Pull request by comingAlive**
---
name: "Pull request"
about: A new pull request
---

### Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/react-moralis/blob/main/SECURITY.md).
- [x] My code is conform the [code style](https://github.com/MoralisWeb3/react-moralis/blob/main/CODE_STYLE.md)
- [x] I have made corresponding changes to the documentation
- [x] I have updated Typescript definitions when needed

### Issue Description

TypeScript throws an error when using `authenticate` from the `useMoralis` hook with `{ type: "sol" }`.

### Solution Description

Add "sol" to AuthType in `_useMoralisAuth.ts`

### CODE REVIEW

**Comment by ErnoW** [comment]
Good one, I actually think we can import the type from the moralis SDK by using
```js
MoralisType.AuthenticationType
```

**Comment by comingAlive** [comment]
updated

**Comment by ErnoW** [comment]
Nice, thanks!

**Review by ErnoW — APPROVED** [review]

**Pull request merged**
