### PR TITLE
fix: types for connector options on authenticate

### PR DESCRIPTION
**Pull request by ErnoW**
---
name: "Pull request"
about: A new pull request
---

### Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/react-moralis/blob/main/SECURITY.md).
- [x] My code is conform the [code style](https://github.com/MoralisWeb3/react-moralis/blob/main/CODE_STYLE.md)
- [x] I have made corresponding changes to the documentation
- [x] I have updated Typescript definitions when needed

### Issue Description

Missing types for different connectors have been added by importing them from the Moralis SDK

### CODE REVIEW

**Comment by EricForgy** [comment]
Cool. Does this help with #206 ?

**Comment by ErnoW** [comment]
> Cool. Does this help with #206 ?

Yes correct. Should resolve that issue.
Be sure to update both `moralis` and `react-moralis`

**Comment by EricForgy** [comment]
Awesome! Thank you 🙏😊

I'll give it a try and close the issue if it works (which I expect it to) 👍

**Pull request merged**
